import type { Restaurant } from "@/types";

/** Demo restaurants shown when Google Maps API key is not set */
export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    place_id: "mock_001",
    name: "老乾杯燒肉 台中文心店",
    address: "台中市南屯區文心南路195號",
    lat: 24.133,
    lng: 120.641,
    google_rating: 4.2,
    total_ratings: 1823,
    cuisine_type: "燒烤",
    has_parking: true,
    price_level: 3,
    is_open: true,
    photo_url: null,
  },
  {
    place_id: "mock_002",
    name: "鼎泰豐 台中新光三越店",
    address: "台中市西屯區台灣大道三段301號B1",
    lat: 24.1618,
    lng: 120.6471,
    google_rating: 4.4,
    total_ratings: 3201,
    cuisine_type: "中式",
    has_parking: true,
    price_level: 3,
    is_open: true,
    photo_url: null,
  },
  {
    place_id: "mock_003",
    name: "春水堂 台中大墩店",
    address: "台中市西區大墩十一街35號",
    lat: 24.1455,
    lng: 120.6429,
    google_rating: 4.1,
    total_ratings: 987,
    cuisine_type: "台式",
    has_parking: false,
    parking_distance_meters: 200,
    price_level: 2,
    is_open: true,
    photo_url: null,
  },
  {
    place_id: "mock_004",
    name: "八方雲集 (示意)",
    address: "台中市北區中清路一段123號",
    lat: 24.1621,
    lng: 120.6702,
    google_rating: 4.0,
    total_ratings: 456,
    cuisine_type: "台式",
    has_parking: false,
    parking_distance_meters: 350,
    price_level: 1,
    is_open: true,
    photo_url: null,
  },
  {
    place_id: "mock_005",
    name: "韓鄉 韓國料理",
    address: "台中市北區崇德路一段631號",
    lat: 24.1698,
    lng: 120.6793,
    google_rating: 4.3,
    total_ratings: 672,
    cuisine_type: "韓式",
    has_parking: true,
    price_level: 2,
    is_open: false,
    photo_url: null,
  },
  {
    place_id: "mock_006",
    name: "義饗食堂 義大利麵",
    address: "台中市西屯區逢甲路3號",
    lat: 24.1809,
    lng: 120.6395,
    google_rating: 4.2,
    total_ratings: 1205,
    cuisine_type: "義大利麵",
    has_parking: false,
    parking_distance_meters: 150,
    price_level: 2,
    is_open: true,
    photo_url: null,
  },
  {
    place_id: "mock_007",
    name: "新光三越台中中港店",
    address: "台中市西屯區台灣大道三段301號",
    lat: 24.162,
    lng: 120.647,
    google_rating: 4.3,
    total_ratings: 5401,
    cuisine_type: "百貨公司",
    has_parking: true,
    price_level: 2,
    is_open: true,
    photo_url: null,
  },
  {
    place_id: "mock_008",
    name: "清水火鍋",
    address: "台中市南區建國南路一段232號",
    lat: 24.1288,
    lng: 120.6741,
    google_rating: 4.5,
    total_ratings: 892,
    cuisine_type: "火鍋",
    has_parking: true,
    price_level: 2,
    is_open: true,
    photo_url: null,
  },
];
